-- CF_COMBAT_ATTACK_NORMAL 	= 1
-- CF_COMBAT_ATTACK_PIERCE 	= 2
-- CF_COMBAT_ATTACK_MAGIC 		= 3
-- CF_COMBAT_ATTACK_SIEGE 		= 4
-- CF_COMBAT_ATTACK_HERO		= 5
-- CF_COMBAT_ATTACK_CHAOS		= 6

-- CF_COMBAT_ARMOR_UNARMED		= 10
-- CF_COMBAT_ARMOR_LIGHT 		= 11
-- CF_COMBAT_ARMOR_MEDIUM 		= 12
-- CF_COMBAT_ARMOR_HEAVY 		= 13
-- CF_COMBAT_ARMOR_FORTIFIED	= 14
-- CF_COMBAT_ARMOR_DIVINE		= 15

-- Combat Constants
CF_DAMAGETYPE_MODIFIERS = {}
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_NORMAL"] = {}
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_PIERCE"] = {}
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_MAGIC"] = {}
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_CHAOS"] = {}
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SIEGE"] = {}
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_HERO"] = {}
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SPELLS"] = {}

CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_NORMAL"]["CF_COMBAT_ARMOR_UNARMED"]   = 1.05
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_NORMAL"]["CF_COMBAT_ARMOR_LIGHT"]     = 0.70
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_NORMAL"]["CF_COMBAT_ARMOR_MEDIUM"]    = 1.75
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_NORMAL"]["CF_COMBAT_ARMOR_HEAVY"]     = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_NORMAL"]["CF_COMBAT_ARMOR_FORTIFIED"] = 0.50
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_NORMAL"]["CF_COMBAT_ARMOR_DIVINE"]    = 0.25

CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_PIERCE"]["CF_COMBAT_ARMOR_UNARMED"]   = 1.05
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_PIERCE"]["CF_COMBAT_ARMOR_LIGHT"]     = 1.75
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_PIERCE"]["CF_COMBAT_ARMOR_MEDIUM"]    = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_PIERCE"]["CF_COMBAT_ARMOR_HEAVY"]     = 0.75
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_PIERCE"]["CF_COMBAT_ARMOR_FORTIFIED"] = 0.40
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_PIERCE"]["CF_COMBAT_ARMOR_DIVINE"]    = 0.25

CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_MAGIC"]["CF_COMBAT_ARMOR_UNARMED"]    = 1.05
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_MAGIC"]["CF_COMBAT_ARMOR_LIGHT"]      = 1.75
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_MAGIC"]["CF_COMBAT_ARMOR_MEDIUM"]     = 0.70
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_MAGIC"]["CF_COMBAT_ARMOR_HEAVY"]      = 1.75
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_MAGIC"]["CF_COMBAT_ARMOR_FORTIFIED"]  = 0.40
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_MAGIC"]["CF_COMBAT_ARMOR_DIVINE"]     = 0.25

CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_CHAOS"]["CF_COMBAT_ARMOR_UNARMED"]    = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_CHAOS"]["CF_COMBAT_ARMOR_LIGHT"]      = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_CHAOS"]["CF_COMBAT_ARMOR_MEDIUM"]     = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_CHAOS"]["CF_COMBAT_ARMOR_HEAVY"]      = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_CHAOS"]["CF_COMBAT_ARMOR_FORTIFIED"]  = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_CHAOS"]["CF_COMBAT_ARMOR_DIVINE"]     = 1.00

CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SIEGE"]["CF_COMBAT_ARMOR_UNARMED"]    = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SIEGE"]["CF_COMBAT_ARMOR_LIGHT"]      = 0.70
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SIEGE"]["CF_COMBAT_ARMOR_MEDIUM"]     = 0.70
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SIEGE"]["CF_COMBAT_ARMOR_HEAVY"]      = 0.70
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SIEGE"]["CF_COMBAT_ARMOR_FORTIFIED"]  = 1.60
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SIEGE"]["CF_COMBAT_ARMOR_DIVINE"]     = 0.20

CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_HERO"]["CF_COMBAT_ARMOR_UNARMED"]     = 1.10
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_HERO"]["CF_COMBAT_ARMOR_LIGHT"]       = 1.10
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_HERO"]["CF_COMBAT_ARMOR_MEDIUM"]      = 1.10
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_HERO"]["CF_COMBAT_ARMOR_HEAVY"]       = 1.10
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_HERO"]["CF_COMBAT_ARMOR_FORTIFIED"]   = 0.60
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_HERO"]["CF_COMBAT_ARMOR_DIVINE"]      = 0.40

CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SPELLS"]["CF_COMBAT_ARMOR_UNARMED"]   = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SPELLS"]["CF_COMBAT_ARMOR_LIGHT"]     = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SPELLS"]["CF_COMBAT_ARMOR_MEDIUM"]    = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SPELLS"]["CF_COMBAT_ARMOR_HEAVY"]     = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SPELLS"]["CF_COMBAT_ARMOR_FORTIFIED"] = 1.00
CF_DAMAGETYPE_MODIFIERS["CF_COMBAT_ATTACK_SPELLS"]["CF_COMBAT_ARMOR_DIVINE"]    = 0.25
